services:
  nestjs_api_prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '3001:3001'
    environment:
      - PORT=3000
      - NODE_ENV=production
    volumes:
      - ./src:/usr/src/app/src
